# Generated by Django 2.2.5 on 2019-09-12 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record_Status',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=254)),
                ('comment', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle_Type',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=254)),
                ('price', models.FloatField()),
                ('comment', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicles_Detail',
            fields=[
                ('plate_No', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('vehicle_type', models.IntegerField()),
                ('owner', models.CharField(max_length=10)),
                ('use_character', models.CharField(max_length=10)),
                ('VIN', models.CharField(max_length=20)),
                ('engine_No', models.CharField(max_length=20)),
                ('comment', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicles_Record',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('vehicle_type', models.IntegerField()),
                ('plate_no', models.CharField(max_length=254)),
                ('price', models.FloatField()),
                ('status', models.IntegerField()),
                ('comment', models.CharField(max_length=254)),
            ],
        ),
    ]
