# Generated by Django 2.2.5 on 2019-09-17 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicles_record',
            name='recorder',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='record_status',
            name='comment',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='vehicle_type',
            name='comment',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='vehicles_record',
            name='comment',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='vehicles_record',
            name='status',
            field=models.IntegerField(blank=True),
        ),
    ]
