# Generated by Django 2.2.5 on 2019-09-18 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20190918_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicles_record',
            name='vehicle_type',
            field=models.CharField(max_length=50),
        ),
    ]
