# Generated by Django 2.2.5 on 2019-10-03 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_vehicles_record_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicles_record',
            name='totle',
            field=models.FloatField(default=0),
        ),
    ]
